#!/bin/bash
# build_release.sh — builds the distributable RekitBox.app and uploads a new GitHub release.
#
# Uses a shell-script .app (not osacompile). A shell script as the MacOS
# executable requires no code signature and runs correctly after a single
# Gatekeeper approval — no "damaged" errors, no binary signing issues.
#
# What the generated .app does:
#   First launch  → opens Terminal, git-clones the repo to ~/RekitBox,
#                   then hands off to launch.sh (which runs setup.sh if needed)
#   Every launch  → runs launch.sh directly (which does git pull + starts server)
#
# Usage:
#   bash build_release.sh              # builds RekitBox.zip in the current dir
#   bash build_release.sh --release    # also creates a new GitHub release and uploads it

set -euo pipefail

REPO_URL="https://github.com/fabledharbinger0993/RekitBox.git"
APP_NAME="RekitBox.app"
ZIP_NAME="RekitBox.zip"
BUILD_DIR="$(mktemp -d)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Parse flags ───────────────────────────────────────────────────────────────
DO_RELEASE=false
for arg in "$@"; do
  [[ "$arg" == "--release" ]] && DO_RELEASE=true
done

# ── Version from latest git tag ───────────────────────────────────────────────
VERSION="$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")"
echo "Building $APP_NAME  version $VERSION"

# ── Create .app bundle structure ──────────────────────────────────────────────
APP_PATH="$BUILD_DIR/$APP_NAME"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

# ── Write the launcher shell script ───────────────────────────────────────────
cat > "$APP_PATH/Contents/MacOS/RekitBox" << LAUNCHER
#!/bin/bash
# RekitBox bootstrap launcher
# First run: clones the repo. Every run: hands off to launch.sh.

PARENT_DIR="\$HOME/RekitBox"
INSTALL_DIR="\$PARENT_DIR/RekitBox"
REPO_URL="$REPO_URL"

if [ -d "\$INSTALL_DIR/.git" ]; then
  # Already installed — hand off to launch.sh (handles git pull + server start)
  bash "\$INSTALL_DIR/launch.sh"
else
  # First install — open Terminal so the user can see clone + setup progress
  CLONE_CMD="mkdir -p '\$PARENT_DIR' && git clone '\$REPO_URL' '\$INSTALL_DIR' && bash '\$INSTALL_DIR/launch.sh'"
  osascript -e "tell application \"Terminal\" to do script \"\$CLONE_CMD\""
  osascript -e "tell application \"Terminal\" to activate"
fi
LAUNCHER
chmod +x "$APP_PATH/Contents/MacOS/RekitBox"
echo "  ✓ Launcher script written"

# ── Write Info.plist ──────────────────────────────────────────────────────────
cat > "$APP_PATH/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>RekitBox</string>
  <key>CFBundleIconFile</key>
  <string>applet</string>
  <key>CFBundleIdentifier</key>
  <string>com.fabledharbinger.rekitbox</string>
  <key>CFBundleName</key>
  <string>RekitBox</string>
  <key>CFBundleDisplayName</key>
  <string>RekitBox</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>1.0.0</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>LSMinimumSystemVersion</key>
  <string>12.0</string>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSAppleEventsUsageDescription</key>
  <string>RekitBox uses Terminal to install dependencies and launch the server.</string>
</dict>
</plist>
PLIST
echo "  ✓ Info.plist written"

# ── Apply RekitBox icon ───────────────────────────────────────────────────────
# Prefer new branded icon, fall back to legacy logo
ICON_SRC="$SCRIPT_DIR/static/icon-rekitbox-app.png"
[[ ! -f "$ICON_SRC" ]] && ICON_SRC="$SCRIPT_DIR/static/RB_LOGO.png"

if [[ -f "$ICON_SRC" ]]; then
  ICONSET_DIR="$BUILD_DIR/rekitbox.iconset"
  mkdir -p "$ICONSET_DIR"
  for size in 16 32 64 128 256 512; do
    sips -z $size $size "$ICON_SRC" --out "$ICONSET_DIR/icon_${size}x${size}.png" &>/dev/null
    double=$((size * 2))
    sips -z $double $double "$ICON_SRC" --out "$ICONSET_DIR/icon_${size}x${size}@2x.png" &>/dev/null
  done
  iconutil -c icns "$ICONSET_DIR" -o "$APP_PATH/Contents/Resources/applet.icns" 2>/dev/null \
    && echo "  ✓ Icon applied" \
    || echo "  ⚠ Icon conversion failed — app will use default icon"
fi

# ── Package into RekitBox.zip ─────────────────────────────────────────────────
ZIP_PATH="$(pwd)/$ZIP_NAME"
(cd "$BUILD_DIR" && zip -qr "$ZIP_PATH" "$APP_NAME")
echo "  ✓ Packaged → $ZIP_PATH"
rm -rf "$BUILD_DIR"

# ── Optionally create a GitHub release ───────────────────────────────────────
if [[ "$DO_RELEASE" == true ]]; then
  echo ""
  echo "Creating GitHub release $VERSION …"

  RELEASE_NOTES="## Download

**↓ Click RekitBox.zip below** — the two \"Source code\" files are auto-generated by GitHub and are not the app.

---

## Install

1. Download **RekitBox.zip** above
2. Unzip — you get **RekitBox.app**
3. Move it to your Desktop or Applications folder
4. Double-click to launch

> **First launch** opens a Terminal window and clones RekitBox, then automatically installs everything needed — Homebrew, \`ffmpeg\`, \`chromaprint\`, and all Python packages. This runs once and takes a few minutes. RekitBox opens in your browser when it's done.

> **Future launches** update RekitBox automatically — no manual downloads needed.

## \"RekitBox can't be opened\"?

This is macOS Gatekeeper — it blocks apps that aren't signed with an Apple Developer certificate. To allow it:

1. Go to **System Settings → Privacy & Security**
2. Scroll down — you'll see *\"RekitBox was blocked from use\"*
3. Click **Open Anyway**

Alternatively, right-click the app → **Open** → **Open Anyway**."

  /opt/homebrew/bin/gh release create "$VERSION" "$ZIP_PATH" \
    --title "RekitBox $VERSION" \
    --notes "$RELEASE_NOTES" \
    --latest 2>/dev/null \
    || /opt/homebrew/bin/gh release upload "$VERSION" "$ZIP_PATH" --clobber

  echo "  ✓ Release $VERSION published"
  echo "  → https://github.com/fabledharbinger0993/RekitBox/releases/tag/$VERSION"
fi

echo ""
echo "Done. $ZIP_NAME is ready."
