"""
RekitBox / icon_utils.py

Apply custom macOS Finder icons to files and folders generated by RekitBox.

Uses NSWorkspace (PyObjC / AppKit) — available on all macOS systems with
the system Python, and installable via `pip install pyobjc-framework-Cocoa`
for virtual-environment Pythons. Every public function silently no-ops when:
  • running on a non-macOS platform
  • PyObjC / AppKit is not importable
  • the icon PNG file is missing from static/

Icon files expected at (relative to this module):
  static/icon-rb-folder.png   — green folder icon  (applied to every new
                                Archive sub-folder created by RekitBox)
  static/icon-rb-file.png     — blue document icon (applied to every new
                                report, savepoint, or log file written)

Public interface:
    set_folder_icon(path: Path) -> None
    set_file_icon(path: Path)   -> None
"""

import logging
import platform
from pathlib import Path

log = logging.getLogger(__name__)

_IS_MACOS: bool = platform.system() == "Darwin"

# Resolve icon paths relative to this file so imports work from any CWD.
_HERE        = Path(__file__).parent
FOLDER_ICON  = _HERE / "static" / "icon-rb-folder.png"
FILE_ICON    = _HERE / "static" / "icon-rb-file.png"


# ── PyObjC helpers ────────────────────────────────────────────────────────────

def _workspace():
    """Return NSWorkspace.sharedWorkspace(), or None if PyObjC is unavailable."""
    if not _IS_MACOS:
        return None
    try:
        from AppKit import NSWorkspace          # noqa: PLC0415
        return NSWorkspace.sharedWorkspace()
    except Exception:
        return None


def _load_ns_image(icon_path: Path):
    """Return an NSImage loaded from icon_path, or None on any failure."""
    if not icon_path.is_file():
        log.debug(
            "RekitBox icon not found at %s — "
            "drop your PNG there to enable custom icons.",
            icon_path,
        )
        return None
    try:
        from AppKit import NSImage              # noqa: PLC0415
        img = NSImage.alloc().initWithContentsOfFile_(str(icon_path))
        return img if img else None
    except Exception as exc:
        log.debug("Could not load icon from %s: %s", icon_path, exc)
        return None


def _apply_icon(target: Path, icon_path: Path) -> None:
    """
    Core: apply icon_path's image as the Finder icon for target.
    Silently no-ops on any failure so it never interrupts a running command.
    """
    ws = _workspace()
    if ws is None:
        return
    img = _load_ns_image(icon_path)
    if img is None:
        return
    try:
        ws.setIcon_forFile_options_(img, str(target), 0)
    except Exception as exc:
        log.debug("Could not set Finder icon on %s: %s", target.name, exc)


# ── Public API ────────────────────────────────────────────────────────────────

def set_folder_icon(path: Path) -> None:
    """
    Apply the RekitBox green-folder icon to path (a directory).

    Called by ensure_archive_structure() after every mkdir so that the
    entire RekitBox Archive tree uses the branded folder appearance in Finder.
    Safe to call on an already-iconified folder — Finder just overwrites.
    """
    _apply_icon(path, FOLDER_ICON)


def set_file_icon(path: Path) -> None:
    """
    Apply the RekitBox blue-document icon to path (a file).

    Called after every report, savepoint, and log file is written so that
    RekitBox-generated files are visually distinct in Finder from the
    user's own audio files and other library assets.
    """
    _apply_icon(path, FILE_ICON)
